# Generated by Django 2.2.7 on 2019-11-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('New', 'new'), ('Used', 'used')], max_length=100),
        ),
    ]
